// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           32
// Async Callback:                       1
// Total number of exported functions:  34

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    farm_extra_rewards_wrapper
    (
        getRewardPerShare
        getRewardReserve
        getFarmingTokenId
        getRewardTokenId
        getPerBlockRewardAmount
        getLastRewardBlockNonce
        getDivisionSafetyConstant
        registerFarmToken
        getFarmTokenId
        getFarmTokenSupply
        addToPauseWhitelist
        removeFromPauseWhitelist
        pause
        resume
        getState
        addAdmin
        removeAdmin
        updateOwnerOrAdmin
        getPermissions
        depositRewardTokens
        withdrawRewardTokens
        getRewardTokens
        getTokenAdditionBlock
        wrapFarmToken
        claimRewards
        unwrapFarmToken
        unwrapAndExitFarm
        addFarms
        removeFarms
        getFarmForFarmToken
        getFarmForFarmingToken
        getFarmConfig
        callBack
    )
}
