// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           25
// Async Callback:                       1
// Total number of exported functions:  27

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    energy_dao
    (
        addFarms
        removeFarms
        getFarmState
        getFarmingTokenId
        getFarmTokenId
        getDivisionSafetyConstant
        getWrappedFarmTokenId
        getUnstakeFarmTokenId
        getUnbondPeriod
        getPenaltyPercent
        enterFarm
        claimFarmRewards
        claimUserRewards
        unstakeFarm
        unbondFarm
        lockEnergyTokens
        claimFeesCollectorRewards
        setEnergyFactoryAddress
        getEnergyFactoryAddress
        issueWrappedToken
        setTransferRoleWrappedToken
        unsetTransferRoleWrappedToken
        getLockedTokenId
        getOldLockedTokenId
        getWrappedTokenId
        callBack
    )
}
